.TH AWESOMESHOT 1 "18 April 2022" "Awesomeshot 1.0.5" "User Commands"
.SH NAME
Awesomeshot
.SH SYNOPSIS
.B awesomeshot
\fI\,[args] [file]\/\fR
.SH DESCRIPTION
Awesomeshot \- A command-line screenshot tool written in bash 5.1.16+
.SH META OPTIONS
\fB\-h, \-\-help\fR
.IP
Show list of command-line options
.TP
\fB\-v, \-\-version\fR
.IP
Show version of awesomeshot
.SH RUN OPTIONS
\fB\-a, \-\-auto\fR
.IP
Run awesomeshot with automatic while take screenshot
.TP
\fB\-m, \-\-manual\fR
.IP
Run awesomeshot with manual (this option require filename)
.TP
\fB\-c, \-\-config\fR
.IP
Generate default config \fI\,awesomeshot.conf\/\fR
.SH "REPORTING BUGS"
Report bugs to
.IP
\fI\,https://github.com/mayTermux/awesomeshot/issues\/\fR
