.TH AWESOMESHOT 1 "20 April 2022" "Awesomeshot 1.0.8" "User Commands"
.SH NAME
Awesomeshot
.SH SYNOPSIS
.B awesomeshot
\fI\,[args] [file]\/\fR
.SH DESCRIPTION
Awesomeshot \- A command-line screenshot tool written in bash 5.1.16+
.SH "HOW AWESOMESHOT WORK?"
\fI\,https://github.com/mayTermux/awesomeshot/issues/2#issuecomment-1052047095\/\fR
.SH "WIKI OR DOCS"
\fI\,https://github.com/mayTermux/awesomeshot/wiki\/\fR
.SH "REPORTING BUGS"
Report bugs to
.IP
\fI\,https://github.com/mayTermux/awesomeshot/issues\/\fR
.SH "SHOWCASE"
Upload your custom config or script
.IP
\fI\,https://github.com/mayTermux/awesomeshot/issues/4\/\fR
.SH META OPTIONS
\fB\-h, \-\-help\fR
.IP
Show list of command-line options
.TP
\fB\-v, \-\-version\fR
.IP
Show version of awesomeshot
.SH RUN OPTIONS
\fB\-a, \-\-auto\fR
.IP
Run awesomeshot with automatic while take screenshot
.TP
\fB\-m, \-\-manual\fR
.IP
Run awesomeshot with manual (this option require filename)
.TP
\fB\-c, \-\-config\fR
.IP
Generate default config \fI\,awesomeshot.conf\/\fR
.SH CONFIG OPTIONS
\fB\/screenshot_result_path\fR
.IP
Make sure when your phone screenshot the result file image\fR
PATH is same with this variable. Default my phone result file\fR
image PATH on 
.IP
"/sdcard/DCIM/Screenshots"
.IP
If not same,\fR
you can edit this variable value\fR
.TP
\fB\/convert_to_png\fR
.IP
This variable serves to set the convert image with file type non PNG, change this value\fR
to blank or whatever for disable function and "yes" for enable function.\fR
Convert to PNG if file not PNG\fR
.TP
\fB\/backup\fR
.IP
This variable serves to function to backup original photo\fR
(screenshot result), change this value to blank or whatever for disable\fR
function and 'yes' for enable function\fR
.TP
\fB\/path_backup\fR
.IP
This variable serves to set the original photo backup PATH\fR
.TP
\fB\/hex_color\fR
.IP
Array Hex Color\fR
.TP
\fB\/convert_titlebar\fR
.IP
This variable serves to convert title bar when editing the image, change this value\fR
to blank or whatever for disable convert and 'yes' for enable function\fR
.TP
\fB\/add_on_img\fR
.IP
This variable serves to set where the title bar place, if 'yes' the title bar add on image,\fR
if blank or whatever the title bar will be added at out of image\fR
.TP
\fB\/width_img & height_img\fR
.IP
This variable serves to set the width and height size of title bar.\fR
.IP
NOTE (Bug Found):
.IP
- Sometimes the title bar result is too big or too small
.IP
width_img=$(magick file_name - format '%w' info:)
.IP
height_img=$(magick file_name - format '%h' info:)
.IP
if (( ${width_img} > ${height_img} )); then
.IP
	height_img=${width_img}
.IP
elif (( ${width_img} < ${height_img} )); then
.IP
	width_img=${height_img}
.IP
fi\fR
.TP
\fB\/titlebar_color\fR
.IP
This variable serves to set titlebar color, if you want to custom the color, you can
change this value with hex color or use the one in the array list.\fR
.TP
\fB\/convert_rounded\fR
.IP
This variable serves to convert rounded corner, change this value
to blank or whatever for disable convert and 'yes' for enable function
\fR
.TP
\fB\/convert_radius\fR
.IP
This variable serves to set how many rounded corners
\fR
.TP
\fB\/convert_first_border\fR
.IP
This variable serves to convert tiny first border (background image) when editing the image,
change this value to blank or whatever for disable convert and 'yes' for enable function
\fR
.TP
\fB\/first_border_color\fR
.IP
This variable serves to set tiny first border color (background image), change this value
to 'none' for transparent background, if you want to custom the color, you can
change this value with hex color or use the one in the array list.
\fR
.TP
\fB\/first_border_size\fR
.IP
This variable serves to set how many size of the first border
NOTE: make sure this value is small, otherwise it will look weird
\fR
.TP
\fB\/convert_second_border\fR
.IP
This variable serves to convert border (background image) when editing the image,
change this value to blank or whatever for disable convert and 'yes' for enable function
\fR
.TP
\fB\/second_border_color\fR
.IP
This variable serves to set border color (background image), change this value
to 'none' for transparent background, if you want to custom the color, you can
change this value with hex color or use the one in the array list.
\fR
.TP
\fB\/second_border_size\fR
.IP
This variable serves to set how many size of the second border
\fR
.TP
\fB\/convert_shadow\fR
.IP
This variable serves to convert the shadow of image, change this value
to blank or whatever for disable function and 'yes' for enable function.
\fR
.TP
\fB\/shadow_color\fR
.IP
This variable serves to set shadow color, if you want to custom the color, you can
change this value with hex color or use the one in the array list.
\fR
.TP
\fb\/shadow_size\fR
.IP
This variable serves to set shadow size, this variable has four values:
shadow_size='75x30+0+30'
that mean:
.IP
- bottom shadow is x75
.IP
- right shadow is +30
.IP
- top shadow is +0
.IP
- left shadow is +30
\fR
.TP
\fb\/convert_footer\fR
.IP
This variable serves to convert the footer text, change this value
to blank or whatever for disable function and 'yes' for enable function.
\fR
.TP
\fb\/footer_text\fR
.IP
This variable serves to set text of footer, if you want to use icon
you can search on Nerd Fonts Website (\fI\,https://www.nerdfonts.com/cheat-sheet\fR)
NOTE: if you use icon from Nerd Fonts, make sure 'footer_font' using nerd fonts to!
\fR
.TP
\fb\/footer_position\fR
.IP
This variable serves to set text position of footer, the value contain 8 wind direction:
- NorthWest
.IP
- North
.IP
- West
.IP
- Center
.IP
- East
.IP
- SouthWest
.IP
- South
.IP
- SouthEast
.IP
NOTE: Default value is 'South'
\fR
.TP
\fb\/footer_xy\fR
.IP
This variable serves to set position of 'X' and 'Y'
\fR
.TP
\fb\/footer_font\fR
.IP
This variable serves to set the font used when converting, you can check the list font
available to use for ImageMagick by command:
.IP
magick convert -list font | grep -iE 'font:.*'
\fR
.TP
\fb\/footer_font_size\fR
.IP
This variable serves to set font size
\fR
.TP
\fb\/footer_foreground\fR
.IP
This variable serves to set the text color, if you want to custom the color, you can
change this value with hex color or use the one in the array list.
\fR
.TP
\fb\/footer_background\fR
.IP
This variable serves to set footer background color (background text), change this value
to 'none' for transparent background, if you want to custom the color, you can
change this value with hex color or use the one in the array list.
\fR
.TP
\fb\/open_image\fR
.IP
This variable serves to open the result of image (when editing finished), change this value
to blank or whatever for disable function and 'yes' for enable function.
\fR