#!/bin/bash

COLOR_BASED="\e[39m"
COLOR_DANGER="\e[91m"
COLOR_WARNING="\e[93m"
COLOR_SUCCESS="\e[92m"
COLOR_SKY="\e[34m"

COLOR_DEFAULT="\e[39m"
COLOR_RESET="\033[0m"

COLOR_WHITE="\e[97m"
COLOR_BLACK="\e[30m"

COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_YELLOW="\e[33m"
COLOR_BLUE="\e[34m"
COLOR_MAGENTA="\e[35m"
COLOR_CYAN="\e[36m"

COLOR_LIGHT_GRAY="\e[37m"
COLOR_DARK_GRAY="\e[90m"
COLOR_LIGHT_RED="\e[91m"
COLOR_LIGHT_GREEN="\e[92m"
COLOR_LIGHT_YELLOW="\e[93m"
COLOR_LIGHT_BLUE="\e[94m"
COLOR_LIGHT_MAGENTA="\e[95m"
COLOR_LIGHT_CYAN="\e[96m"

COLOR_BOLD_MAGENTA="\033[1;35m"
COLOR_BOLD_GREEN="\033[1;32m"
COLOR_BOLD_WHITE="\033[1;37m"
COLOR_BOLD_BLUE="\033[1;34m"
COLOR_BOLD_RED="\033[1;31m"
COLOR_BOLD_YELLOW="\033[1;33m"
COLOR_BOLD_CYAN="\033[1;36m"

COLOR_BACKGROUND_YELLOW="\033[1;43;33m"
COLOR_BACKGROUND_BLUE="\033[1;44;97m"
COLOR_BACKGROUND_RED="\033[1;41;97m"
COLOR_BACKGROUND_WHITE="\033[1;47;37m"
COLOR_BACKGROUND_BLACK="\033[1;40;30m"

BLUE=$(tput setaf 4)
GRAY=$(tput setaf 236)
RESET=$(tput sgr0)

export COLOR_BASED COLOR_DANGER COLOR_WARNING COLOR_SUCCESS COLOR_SKY COLOR_DEFAULT COLOR_RESET COLOR_WHITE COLOR_BLACK COLOR_RED COLOR_GREEN \
COLOR_YELLOW COLOR_BLUE COLOR_MAGENTA COLOR_CYAN COLOR_LIGHT_GRAY COLOR_DARK_GRAY COLOR_LIGHT_RED COLOR_LIGHT_GREEN \
COLOR_LIGHT_YELLOW COLOR_LIGHT_BLUE COLOR_LIGHT_MAGENTA COLOR_LIGHT_CYAN COLOR_BOLD_MAGENTA COLOR_BOLD_GREEN COLOR_BOLD_WHITE \
COLOR_BOLD_BLUE COLOR_BOLD_RED COLOR_BOLD_YELLOW COLOR_BOLD_CYAN COLOR_BACKGROUND_YELLOW COLOR_BACKGROUND_BLUE \
COLOR_BACKGROUND_RED COLOR_BACKGROUND_WHITE COLOR_BACKGROUND_BLACK BLUE GRAY RESET